/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * 债券余额数据表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BondBalanceChange implements Serializable {

    private static final long serialVersionUID = -75441557;

    private ULong         id;
    private ULong         bondUniCode;
    private LocalDate     bulletinDate;
    private LocalDate     changeDate;
    private UShort        changeReason;
    private BigDecimal    changeAmount;
    private BigDecimal    bondBalance;
    private UByte         validStatus;
    private ULong         updateBy;
    private UByte         dataSource;
    private ULong         dataId;
    private String        rowUniqueKey;
    private LocalDateTime updateTime;
    private LocalDateTime createTime;

    public BondBalanceChange() {}

    public BondBalanceChange(BondBalanceChange value) {
        this.id = value.id;
        this.bondUniCode = value.bondUniCode;
        this.bulletinDate = value.bulletinDate;
        this.changeDate = value.changeDate;
        this.changeReason = value.changeReason;
        this.changeAmount = value.changeAmount;
        this.bondBalance = value.bondBalance;
        this.validStatus = value.validStatus;
        this.updateBy = value.updateBy;
        this.dataSource = value.dataSource;
        this.dataId = value.dataId;
        this.rowUniqueKey = value.rowUniqueKey;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
    }

    public BondBalanceChange(
        ULong         id,
        ULong         bondUniCode,
        LocalDate     bulletinDate,
        LocalDate     changeDate,
        UShort        changeReason,
        BigDecimal    changeAmount,
        BigDecimal    bondBalance,
        UByte         validStatus,
        ULong         updateBy,
        UByte         dataSource,
        ULong         dataId,
        String        rowUniqueKey,
        LocalDateTime updateTime,
        LocalDateTime createTime
    ) {
        this.id = id;
        this.bondUniCode = bondUniCode;
        this.bulletinDate = bulletinDate;
        this.changeDate = changeDate;
        this.changeReason = changeReason;
        this.changeAmount = changeAmount;
        this.bondBalance = bondBalance;
        this.validStatus = validStatus;
        this.updateBy = updateBy;
        this.dataSource = dataSource;
        this.dataId = dataId;
        this.rowUniqueKey = rowUniqueKey;
        this.updateTime = updateTime;
        this.createTime = createTime;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public ULong getBondUniCode() {
        return this.bondUniCode;
    }

    public void setBondUniCode(ULong bondUniCode) {
        this.bondUniCode = bondUniCode;
    }

    public LocalDate getBulletinDate() {
        return this.bulletinDate;
    }

    public void setBulletinDate(LocalDate bulletinDate) {
        this.bulletinDate = bulletinDate;
    }

    public LocalDate getChangeDate() {
        return this.changeDate;
    }

    public void setChangeDate(LocalDate changeDate) {
        this.changeDate = changeDate;
    }

    public UShort getChangeReason() {
        return this.changeReason;
    }

    public void setChangeReason(UShort changeReason) {
        this.changeReason = changeReason;
    }

    public BigDecimal getChangeAmount() {
        return this.changeAmount;
    }

    public void setChangeAmount(BigDecimal changeAmount) {
        this.changeAmount = changeAmount;
    }

    public BigDecimal getBondBalance() {
        return this.bondBalance;
    }

    public void setBondBalance(BigDecimal bondBalance) {
        this.bondBalance = bondBalance;
    }

    public UByte getValidStatus() {
        return this.validStatus;
    }

    public void setValidStatus(UByte validStatus) {
        this.validStatus = validStatus;
    }

    public ULong getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(ULong updateBy) {
        this.updateBy = updateBy;
    }

    public UByte getDataSource() {
        return this.dataSource;
    }

    public void setDataSource(UByte dataSource) {
        this.dataSource = dataSource;
    }

    public ULong getDataId() {
        return this.dataId;
    }

    public void setDataId(ULong dataId) {
        this.dataId = dataId;
    }

    public String getRowUniqueKey() {
        return this.rowUniqueKey;
    }

    public void setRowUniqueKey(String rowUniqueKey) {
        this.rowUniqueKey = rowUniqueKey;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BondBalanceChange (");

        sb.append(id);
        sb.append(", ").append(bondUniCode);
        sb.append(", ").append(bulletinDate);
        sb.append(", ").append(changeDate);
        sb.append(", ").append(changeReason);
        sb.append(", ").append(changeAmount);
        sb.append(", ").append(bondBalance);
        sb.append(", ").append(validStatus);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(dataSource);
        sb.append(", ").append(dataId);
        sb.append(", ").append(rowUniqueKey);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);

        sb.append(")");
        return sb.toString();
    }
}
