/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BondSizeChg implements Serializable {

    private static final long serialVersionUID = -977540336;

    private Long          id;
    private String        bondId;
    private LocalDate     publishDate;
    private LocalDate     changeDate;
    private BigDecimal    changeSize;
    private BigDecimal    remainSize;
    private String        changeReasonCd;
    private LocalDateTime updateTime;
    private Long          tmstamp;

    public BondSizeChg() {}

    public BondSizeChg(BondSizeChg value) {
        this.id = value.id;
        this.bondId = value.bondId;
        this.publishDate = value.publishDate;
        this.changeDate = value.changeDate;
        this.changeSize = value.changeSize;
        this.remainSize = value.remainSize;
        this.changeReasonCd = value.changeReasonCd;
        this.updateTime = value.updateTime;
        this.tmstamp = value.tmstamp;
    }

    public BondSizeChg(
        Long          id,
        String        bondId,
        LocalDate     publishDate,
        LocalDate     changeDate,
        BigDecimal    changeSize,
        BigDecimal    remainSize,
        String        changeReasonCd,
        LocalDateTime updateTime,
        Long          tmstamp
    ) {
        this.id = id;
        this.bondId = bondId;
        this.publishDate = publishDate;
        this.changeDate = changeDate;
        this.changeSize = changeSize;
        this.remainSize = remainSize;
        this.changeReasonCd = changeReasonCd;
        this.updateTime = updateTime;
        this.tmstamp = tmstamp;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBondId() {
        return this.bondId;
    }

    public void setBondId(String bondId) {
        this.bondId = bondId;
    }

    public LocalDate getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(LocalDate publishDate) {
        this.publishDate = publishDate;
    }

    public LocalDate getChangeDate() {
        return this.changeDate;
    }

    public void setChangeDate(LocalDate changeDate) {
        this.changeDate = changeDate;
    }

    public BigDecimal getChangeSize() {
        return this.changeSize;
    }

    public void setChangeSize(BigDecimal changeSize) {
        this.changeSize = changeSize;
    }

    public BigDecimal getRemainSize() {
        return this.remainSize;
    }

    public void setRemainSize(BigDecimal remainSize) {
        this.remainSize = remainSize;
    }

    public String getChangeReasonCd() {
        return this.changeReasonCd;
    }

    public void setChangeReasonCd(String changeReasonCd) {
        this.changeReasonCd = changeReasonCd;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Long getTmstamp() {
        return this.tmstamp;
    }

    public void setTmstamp(Long tmstamp) {
        this.tmstamp = tmstamp;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BondSizeChg (");

        sb.append(id);
        sb.append(", ").append(bondId);
        sb.append(", ").append(publishDate);
        sb.append(", ").append(changeDate);
        sb.append(", ").append(changeSize);
        sb.append(", ").append(remainSize);
        sb.append(", ").append(changeReasonCd);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(tmstamp);

        sb.append(")");
        return sb.toString();
    }
}
