/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * 公司担保基本信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComGuarInfo implements Serializable {

    private static final long serialVersionUID = 1284417100;

    private ULong      id;
    private Long       comUniCode;
    private String     comFullName;
    private Short      reportYear;
    private Byte       reportQuarter;
    private Integer    guaranteeBondNumber;
    private BigDecimal guaranteeBp;
    private BigDecimal bondCouponRateAvg;
    private BigDecimal guarLiabilityBalanceGr;
    private BigDecimal udicRadio;
    private BigDecimal privateEnterpriseRatio;
    private BigDecimal outsideProvinceRatio;
    private UByte      privateEnterpriseStatus;
    private UByte      outsideProvinceStatus;
    private ULong      provinceUniCode;
    private BigDecimal comCurrentBondsBalance;
    private UShort     comExtRatingFilterMapping;
    private String     comExtCreditRatingComName;
    private LocalDate  establishDate;
    private Byte       deleted;
    private Long       registeredCapital;
    private UShort     businessNature;
    private LocalDate  reportDate;

    public ComGuarInfo() {}

    public ComGuarInfo(ComGuarInfo value) {
        this.id = value.id;
        this.comUniCode = value.comUniCode;
        this.comFullName = value.comFullName;
        this.reportYear = value.reportYear;
        this.reportQuarter = value.reportQuarter;
        this.guaranteeBondNumber = value.guaranteeBondNumber;
        this.guaranteeBp = value.guaranteeBp;
        this.bondCouponRateAvg = value.bondCouponRateAvg;
        this.guarLiabilityBalanceGr = value.guarLiabilityBalanceGr;
        this.udicRadio = value.udicRadio;
        this.privateEnterpriseRatio = value.privateEnterpriseRatio;
        this.outsideProvinceRatio = value.outsideProvinceRatio;
        this.privateEnterpriseStatus = value.privateEnterpriseStatus;
        this.outsideProvinceStatus = value.outsideProvinceStatus;
        this.provinceUniCode = value.provinceUniCode;
        this.comCurrentBondsBalance = value.comCurrentBondsBalance;
        this.comExtRatingFilterMapping = value.comExtRatingFilterMapping;
        this.comExtCreditRatingComName = value.comExtCreditRatingComName;
        this.establishDate = value.establishDate;
        this.deleted = value.deleted;
        this.registeredCapital = value.registeredCapital;
        this.businessNature = value.businessNature;
        this.reportDate = value.reportDate;
    }

    public ComGuarInfo(
        ULong      id,
        Long       comUniCode,
        String     comFullName,
        Short      reportYear,
        Byte       reportQuarter,
        Integer    guaranteeBondNumber,
        BigDecimal guaranteeBp,
        BigDecimal bondCouponRateAvg,
        BigDecimal guarLiabilityBalanceGr,
        BigDecimal udicRadio,
        BigDecimal privateEnterpriseRatio,
        BigDecimal outsideProvinceRatio,
        UByte      privateEnterpriseStatus,
        UByte      outsideProvinceStatus,
        ULong      provinceUniCode,
        BigDecimal comCurrentBondsBalance,
        UShort     comExtRatingFilterMapping,
        String     comExtCreditRatingComName,
        LocalDate  establishDate,
        Byte       deleted,
        Long       registeredCapital,
        UShort     businessNature,
        LocalDate  reportDate
    ) {
        this.id = id;
        this.comUniCode = comUniCode;
        this.comFullName = comFullName;
        this.reportYear = reportYear;
        this.reportQuarter = reportQuarter;
        this.guaranteeBondNumber = guaranteeBondNumber;
        this.guaranteeBp = guaranteeBp;
        this.bondCouponRateAvg = bondCouponRateAvg;
        this.guarLiabilityBalanceGr = guarLiabilityBalanceGr;
        this.udicRadio = udicRadio;
        this.privateEnterpriseRatio = privateEnterpriseRatio;
        this.outsideProvinceRatio = outsideProvinceRatio;
        this.privateEnterpriseStatus = privateEnterpriseStatus;
        this.outsideProvinceStatus = outsideProvinceStatus;
        this.provinceUniCode = provinceUniCode;
        this.comCurrentBondsBalance = comCurrentBondsBalance;
        this.comExtRatingFilterMapping = comExtRatingFilterMapping;
        this.comExtCreditRatingComName = comExtCreditRatingComName;
        this.establishDate = establishDate;
        this.deleted = deleted;
        this.registeredCapital = registeredCapital;
        this.businessNature = businessNature;
        this.reportDate = reportDate;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public Long getComUniCode() {
        return this.comUniCode;
    }

    public void setComUniCode(Long comUniCode) {
        this.comUniCode = comUniCode;
    }

    public String getComFullName() {
        return this.comFullName;
    }

    public void setComFullName(String comFullName) {
        this.comFullName = comFullName;
    }

    public Short getReportYear() {
        return this.reportYear;
    }

    public void setReportYear(Short reportYear) {
        this.reportYear = reportYear;
    }

    public Byte getReportQuarter() {
        return this.reportQuarter;
    }

    public void setReportQuarter(Byte reportQuarter) {
        this.reportQuarter = reportQuarter;
    }

    public Integer getGuaranteeBondNumber() {
        return this.guaranteeBondNumber;
    }

    public void setGuaranteeBondNumber(Integer guaranteeBondNumber) {
        this.guaranteeBondNumber = guaranteeBondNumber;
    }

    public BigDecimal getGuaranteeBp() {
        return this.guaranteeBp;
    }

    public void setGuaranteeBp(BigDecimal guaranteeBp) {
        this.guaranteeBp = guaranteeBp;
    }

    public BigDecimal getBondCouponRateAvg() {
        return this.bondCouponRateAvg;
    }

    public void setBondCouponRateAvg(BigDecimal bondCouponRateAvg) {
        this.bondCouponRateAvg = bondCouponRateAvg;
    }

    public BigDecimal getGuarLiabilityBalanceGr() {
        return this.guarLiabilityBalanceGr;
    }

    public void setGuarLiabilityBalanceGr(BigDecimal guarLiabilityBalanceGr) {
        this.guarLiabilityBalanceGr = guarLiabilityBalanceGr;
    }

    public BigDecimal getUdicRadio() {
        return this.udicRadio;
    }

    public void setUdicRadio(BigDecimal udicRadio) {
        this.udicRadio = udicRadio;
    }

    public BigDecimal getPrivateEnterpriseRatio() {
        return this.privateEnterpriseRatio;
    }

    public void setPrivateEnterpriseRatio(BigDecimal privateEnterpriseRatio) {
        this.privateEnterpriseRatio = privateEnterpriseRatio;
    }

    public BigDecimal getOutsideProvinceRatio() {
        return this.outsideProvinceRatio;
    }

    public void setOutsideProvinceRatio(BigDecimal outsideProvinceRatio) {
        this.outsideProvinceRatio = outsideProvinceRatio;
    }

    public UByte getPrivateEnterpriseStatus() {
        return this.privateEnterpriseStatus;
    }

    public void setPrivateEnterpriseStatus(UByte privateEnterpriseStatus) {
        this.privateEnterpriseStatus = privateEnterpriseStatus;
    }

    public UByte getOutsideProvinceStatus() {
        return this.outsideProvinceStatus;
    }

    public void setOutsideProvinceStatus(UByte outsideProvinceStatus) {
        this.outsideProvinceStatus = outsideProvinceStatus;
    }

    public ULong getProvinceUniCode() {
        return this.provinceUniCode;
    }

    public void setProvinceUniCode(ULong provinceUniCode) {
        this.provinceUniCode = provinceUniCode;
    }

    public BigDecimal getComCurrentBondsBalance() {
        return this.comCurrentBondsBalance;
    }

    public void setComCurrentBondsBalance(BigDecimal comCurrentBondsBalance) {
        this.comCurrentBondsBalance = comCurrentBondsBalance;
    }

    public UShort getComExtRatingFilterMapping() {
        return this.comExtRatingFilterMapping;
    }

    public void setComExtRatingFilterMapping(UShort comExtRatingFilterMapping) {
        this.comExtRatingFilterMapping = comExtRatingFilterMapping;
    }

    public String getComExtCreditRatingComName() {
        return this.comExtCreditRatingComName;
    }

    public void setComExtCreditRatingComName(String comExtCreditRatingComName) {
        this.comExtCreditRatingComName = comExtCreditRatingComName;
    }

    public LocalDate getEstablishDate() {
        return this.establishDate;
    }

    public void setEstablishDate(LocalDate establishDate) {
        this.establishDate = establishDate;
    }

    public Byte getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    public Long getRegisteredCapital() {
        return this.registeredCapital;
    }

    public void setRegisteredCapital(Long registeredCapital) {
        this.registeredCapital = registeredCapital;
    }

    public UShort getBusinessNature() {
        return this.businessNature;
    }

    public void setBusinessNature(UShort businessNature) {
        this.businessNature = businessNature;
    }

    public LocalDate getReportDate() {
        return this.reportDate;
    }

    public void setReportDate(LocalDate reportDate) {
        this.reportDate = reportDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ComGuarInfo (");

        sb.append(id);
        sb.append(", ").append(comUniCode);
        sb.append(", ").append(comFullName);
        sb.append(", ").append(reportYear);
        sb.append(", ").append(reportQuarter);
        sb.append(", ").append(guaranteeBondNumber);
        sb.append(", ").append(guaranteeBp);
        sb.append(", ").append(bondCouponRateAvg);
        sb.append(", ").append(guarLiabilityBalanceGr);
        sb.append(", ").append(udicRadio);
        sb.append(", ").append(privateEnterpriseRatio);
        sb.append(", ").append(outsideProvinceRatio);
        sb.append(", ").append(privateEnterpriseStatus);
        sb.append(", ").append(outsideProvinceStatus);
        sb.append(", ").append(provinceUniCode);
        sb.append(", ").append(comCurrentBondsBalance);
        sb.append(", ").append(comExtRatingFilterMapping);
        sb.append(", ").append(comExtCreditRatingComName);
        sb.append(", ").append(establishDate);
        sb.append(", ").append(deleted);
        sb.append(", ").append(registeredCapital);
        sb.append(", ").append(businessNature);
        sb.append(", ").append(reportDate);

        sb.append(")");
        return sb.toString();
    }
}
