/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Good implements Serializable {

    private static final long serialVersionUID = -1315262582;

    private Integer       id;
    private String        sn;
    private String        name;
    private String        alias;
    private String        picture;
    private Integer       stock;
    private BigDecimal    costPrice;
    private BigDecimal    price;
    private Byte          status;
    private String        operate;
    private LocalDateTime created;
    private LocalDateTime updated;

    public Good() {}

    public Good(Good value) {
        this.id = value.id;
        this.sn = value.sn;
        this.name = value.name;
        this.alias = value.alias;
        this.picture = value.picture;
        this.stock = value.stock;
        this.costPrice = value.costPrice;
        this.price = value.price;
        this.status = value.status;
        this.operate = value.operate;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Good(
        Integer       id,
        String        sn,
        String        name,
        String        alias,
        String        picture,
        Integer       stock,
        BigDecimal    costPrice,
        BigDecimal    price,
        Byte          status,
        String        operate,
        LocalDateTime created,
        LocalDateTime updated
    ) {
        this.id = id;
        this.sn = sn;
        this.name = name;
        this.alias = alias;
        this.picture = picture;
        this.stock = stock;
        this.costPrice = costPrice;
        this.price = price;
        this.status = status;
        this.operate = operate;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSn() {
        return this.sn;
    }

    public void setSn(String sn) {
        this.sn = sn;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAlias() {
        return this.alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public Integer getStock() {
        return this.stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public BigDecimal getCostPrice() {
        return this.costPrice;
    }

    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Byte getStatus() {
        return this.status;
    }

    public void setStatus(Byte status) {
        this.status = status;
    }

    public String getOperate() {
        return this.operate;
    }

    public void setOperate(String operate) {
        this.operate = operate;
    }

    public LocalDateTime getCreated() {
        return this.created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public LocalDateTime getUpdated() {
        return this.updated;
    }

    public void setUpdated(LocalDateTime updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Good (");

        sb.append(id);
        sb.append(", ").append(sn);
        sb.append(", ").append(name);
        sb.append(", ").append(alias);
        sb.append(", ").append(picture);
        sb.append(", ").append(stock);
        sb.append(", ").append(costPrice);
        sb.append(", ").append(price);
        sb.append(", ").append(status);
        sb.append(", ").append(operate);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
