/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 百万数据导入导出测试
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MillionsData implements Serializable {

    private static final long serialVersionUID = 654103357;

    private Integer       id;
    private Long          staffNo;
    private BigDecimal    salary;
    private LocalDateTime startTime;
    private LocalDateTime endTime;

    public MillionsData() {}

    public MillionsData(MillionsData value) {
        this.id = value.id;
        this.staffNo = value.staffNo;
        this.salary = value.salary;
        this.startTime = value.startTime;
        this.endTime = value.endTime;
    }

    public MillionsData(
        Integer       id,
        Long          staffNo,
        BigDecimal    salary,
        LocalDateTime startTime,
        LocalDateTime endTime
    ) {
        this.id = id;
        this.staffNo = staffNo;
        this.salary = salary;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getStaffNo() {
        return this.staffNo;
    }

    public void setStaffNo(Long staffNo) {
        this.staffNo = staffNo;
    }

    public BigDecimal getSalary() {
        return this.salary;
    }

    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MillionsData (");

        sb.append(id);
        sb.append(", ").append(staffNo);
        sb.append(", ").append(salary);
        sb.append(", ").append(startTime);
        sb.append(", ").append(endTime);

        sb.append(")");
        return sb.toString();
    }
}
