/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.JSON;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParseTemplate implements Serializable {

    private static final long serialVersionUID = 1884290419;

    private String        id;
    private String        createBy;
    private LocalDateTime createTime;
    private Byte          deleted;
    private Integer       revision;
    private String        updateBy;
    private LocalDateTime updateTime;
    private JSON          parseDataSetting;
    private String        parseTemplateName;
    private String        pwoType;
    private String        parseTemplateCode;
    private Double        version;

    public ParseTemplate() {}

    public ParseTemplate(ParseTemplate value) {
        this.id = value.id;
        this.createBy = value.createBy;
        this.createTime = value.createTime;
        this.deleted = value.deleted;
        this.revision = value.revision;
        this.updateBy = value.updateBy;
        this.updateTime = value.updateTime;
        this.parseDataSetting = value.parseDataSetting;
        this.parseTemplateName = value.parseTemplateName;
        this.pwoType = value.pwoType;
        this.parseTemplateCode = value.parseTemplateCode;
        this.version = value.version;
    }

    public ParseTemplate(
        String        id,
        String        createBy,
        LocalDateTime createTime,
        Byte          deleted,
        Integer       revision,
        String        updateBy,
        LocalDateTime updateTime,
        JSON          parseDataSetting,
        String        parseTemplateName,
        String        pwoType,
        String        parseTemplateCode,
        Double        version
    ) {
        this.id = id;
        this.createBy = createBy;
        this.createTime = createTime;
        this.deleted = deleted;
        this.revision = revision;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
        this.parseDataSetting = parseDataSetting;
        this.parseTemplateName = parseTemplateName;
        this.pwoType = pwoType;
        this.parseTemplateCode = parseTemplateCode;
        this.version = version;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Byte getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    public Integer getRevision() {
        return this.revision;
    }

    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public JSON getParseDataSetting() {
        return this.parseDataSetting;
    }

    public void setParseDataSetting(JSON parseDataSetting) {
        this.parseDataSetting = parseDataSetting;
    }

    public String getParseTemplateName() {
        return this.parseTemplateName;
    }

    public void setParseTemplateName(String parseTemplateName) {
        this.parseTemplateName = parseTemplateName;
    }

    public String getPwoType() {
        return this.pwoType;
    }

    public void setPwoType(String pwoType) {
        this.pwoType = pwoType;
    }

    public String getParseTemplateCode() {
        return this.parseTemplateCode;
    }

    public void setParseTemplateCode(String parseTemplateCode) {
        this.parseTemplateCode = parseTemplateCode;
    }

    public Double getVersion() {
        return this.version;
    }

    public void setVersion(Double version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ParseTemplate (");

        sb.append(id);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createTime);
        sb.append(", ").append(deleted);
        sb.append(", ").append(revision);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(parseDataSetting);
        sb.append(", ").append(parseTemplateName);
        sb.append(", ").append(pwoType);
        sb.append(", ").append(parseTemplateCode);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
