/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student implements Serializable {

    private static final long serialVersionUID = 1104328795;

    private Integer sId;
    private String  sname;
    private Integer sage;
    private String  sgender;

    public Student() {}

    public Student(Student value) {
        this.sId = value.sId;
        this.sname = value.sname;
        this.sage = value.sage;
        this.sgender = value.sgender;
    }

    public Student(
        Integer sId,
        String  sname,
        Integer sage,
        String  sgender
    ) {
        this.sId = sId;
        this.sname = sname;
        this.sage = sage;
        this.sgender = sgender;
    }

    public Integer getSId() {
        return this.sId;
    }

    public void setSId(Integer sId) {
        this.sId = sId;
    }

    public String getSname() {
        return this.sname;
    }

    public void setSname(String sname) {
        this.sname = sname;
    }

    public Integer getSage() {
        return this.sage;
    }

    public void setSage(Integer sage) {
        this.sage = sage;
    }

    public String getSgender() {
        return this.sgender;
    }

    public void setSgender(String sgender) {
        this.sgender = sgender;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Student (");

        sb.append(sId);
        sb.append(", ").append(sname);
        sb.append(", ").append(sage);
        sb.append(", ").append(sgender);

        sb.append(")");
        return sb.toString();
    }
}
