/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.daos;


import com.pluto.millionsExport.jooqData.tables.BondBalanceChange;
import com.pluto.millionsExport.jooqData.tables.records.BondBalanceChangeRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * 债券余额数据表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BondBalanceChangeDao extends DAOImpl<BondBalanceChangeRecord, com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange, ULong> {

    /**
     * Create a new BondBalanceChangeDao without any configuration
     */
    public BondBalanceChangeDao() {
        super(BondBalanceChange.BOND_BALANCE_CHANGE, com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange.class);
    }

    /**
     * Create a new BondBalanceChangeDao with an attached configuration
     */
    public BondBalanceChangeDao(Configuration configuration) {
        super(BondBalanceChange.BOND_BALANCE_CHANGE, com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange.class, configuration);
    }

    @Override
    public ULong getId(com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchById(ULong... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange fetchOneById(ULong value) {
        return fetchOne(BondBalanceChange.BOND_BALANCE_CHANGE.ID, value);
    }

    /**
     * Fetch records that have <code>bond_uni_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfBondUniCode(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.BOND_UNI_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bond_uni_code IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByBondUniCode(ULong... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.BOND_UNI_CODE, values);
    }

    /**
     * Fetch records that have <code>bulletin_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfBulletinDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.BULLETIN_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bulletin_date IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByBulletinDate(LocalDate... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.BULLETIN_DATE, values);
    }

    /**
     * Fetch records that have <code>change_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfChangeDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.CHANGE_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>change_date IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByChangeDate(LocalDate... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.CHANGE_DATE, values);
    }

    /**
     * Fetch records that have <code>change_reason BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfChangeReason(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.CHANGE_REASON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>change_reason IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByChangeReason(UShort... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.CHANGE_REASON, values);
    }

    /**
     * Fetch records that have <code>change_amount BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfChangeAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.CHANGE_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>change_amount IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByChangeAmount(BigDecimal... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.CHANGE_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>bond_balance BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfBondBalance(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.BOND_BALANCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bond_balance IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByBondBalance(BigDecimal... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.BOND_BALANCE, values);
    }

    /**
     * Fetch records that have <code>valid_status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfValidStatus(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.VALID_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>valid_status IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByValidStatus(UByte... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.VALID_STATUS, values);
    }

    /**
     * Fetch records that have <code>update_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfUpdateBy(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.UPDATE_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByUpdateBy(ULong... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>data_source BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfDataSource(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.DATA_SOURCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>data_source IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByDataSource(UByte... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.DATA_SOURCE, values);
    }

    /**
     * Fetch records that have <code>data_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfDataId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.DATA_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>data_id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByDataId(ULong... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.DATA_ID, values);
    }

    /**
     * Fetch records that have <code>row_unique_key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfRowUniqueKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.ROW_UNIQUE_KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>row_unique_key IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByRowUniqueKey(String... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.ROW_UNIQUE_KEY, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(BondBalanceChange.BOND_BALANCE_CHANGE.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondBalanceChange> fetchByCreateTime(LocalDateTime... values) {
        return fetch(BondBalanceChange.BOND_BALANCE_CHANGE.CREATE_TIME, values);
    }
}
