/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.daos;


import com.pluto.millionsExport.jooqData.tables.BondSizeChg;
import com.pluto.millionsExport.jooqData.tables.records.BondSizeChgRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BondSizeChgDao extends DAOImpl<BondSizeChgRecord, com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg, Long> {

    /**
     * Create a new BondSizeChgDao without any configuration
     */
    public BondSizeChgDao() {
        super(BondSizeChg.BOND_SIZE_CHG, com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg.class);
    }

    /**
     * Create a new BondSizeChgDao with an attached configuration
     */
    public BondSizeChgDao(Configuration configuration) {
        super(BondSizeChg.BOND_SIZE_CHG, com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg.class, configuration);
    }

    @Override
    public Long getId(com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchById(Long... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg fetchOneById(Long value) {
        return fetchOne(BondSizeChg.BOND_SIZE_CHG.ID, value);
    }

    /**
     * Fetch records that have <code>BOND_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfBondId(String lowerInclusive, String upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.BOND_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>BOND_ID IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByBondId(String... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.BOND_ID, values);
    }

    /**
     * Fetch records that have <code>PUBLISH_DATE BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfPublishDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.PUBLISH_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>PUBLISH_DATE IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByPublishDate(LocalDate... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.PUBLISH_DATE, values);
    }

    /**
     * Fetch records that have <code>CHANGE_DATE BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfChangeDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.CHANGE_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CHANGE_DATE IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByChangeDate(LocalDate... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.CHANGE_DATE, values);
    }

    /**
     * Fetch records that have <code>CHANGE_SIZE BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfChangeSize(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.CHANGE_SIZE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CHANGE_SIZE IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByChangeSize(BigDecimal... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.CHANGE_SIZE, values);
    }

    /**
     * Fetch records that have <code>REMAIN_SIZE BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfRemainSize(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.REMAIN_SIZE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>REMAIN_SIZE IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByRemainSize(BigDecimal... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.REMAIN_SIZE, values);
    }

    /**
     * Fetch records that have <code>CHANGE_REASON_CD BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfChangeReasonCd(String lowerInclusive, String upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.CHANGE_REASON_CD, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>CHANGE_REASON_CD IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByChangeReasonCd(String... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.CHANGE_REASON_CD, values);
    }

    /**
     * Fetch records that have <code>UPDATE_TIME BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATE_TIME IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>TMSTAMP BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchRangeOfTmstamp(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondSizeChg.BOND_SIZE_CHG.TMSTAMP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TMSTAMP IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.BondSizeChg> fetchByTmstamp(Long... values) {
        return fetch(BondSizeChg.BOND_SIZE_CHG.TMSTAMP, values);
    }
}
