/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.daos;


import com.pluto.millionsExport.jooqData.tables.TrackingRecord;
import com.pluto.millionsExport.jooqData.tables.records.TrackingRecordRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 埋点记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackingRecordDao extends DAOImpl<TrackingRecordRecord, com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord, String> {

    /**
     * Create a new TrackingRecordDao without any configuration
     */
    public TrackingRecordDao() {
        super(TrackingRecord.TRACKING_RECORD, com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord.class);
    }

    /**
     * Create a new TrackingRecordDao with an attached configuration
     */
    public TrackingRecordDao(Configuration configuration) {
        super(TrackingRecord.TRACKING_RECORD, com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord.class, configuration);
    }

    @Override
    public String getId(com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchById(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord fetchOneById(String value) {
        return fetchOne(TrackingRecord.TRACKING_RECORD.ID, value);
    }

    /**
     * Fetch records that have <code>tracking_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfTrackingId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.TRACKING_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tracking_id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByTrackingId(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.TRACKING_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfUserId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByUserId(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.USER_ID, values);
    }

    /**
     * Fetch records that have <code>open_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfOpenId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.OPEN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>open_id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByOpenId(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.OPEN_ID, values);
    }

    /**
     * Fetch records that have <code>patient_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfPatientId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.PATIENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>patient_id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByPatientId(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.PATIENT_ID, values);
    }

    /**
     * Fetch records that have <code>physician_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfPhysicianId(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.PHYSICIAN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>physician_id IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByPhysicianId(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.PHYSICIAN_ID, values);
    }

    /**
     * Fetch records that have <code>event_type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfEventType(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.EVENT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>event_type IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByEventType(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.EVENT_TYPE, values);
    }

    /**
     * Fetch records that have <code>create_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfCreateBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.CREATE_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_by IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByCreateBy(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.CREATE_BY, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByCreateTime(LocalDateTime... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfUpdateBy(String lowerInclusive, String upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.UPDATE_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByUpdateBy(String... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>revision BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfRevision(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.REVISION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>revision IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByRevision(Integer... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.REVISION, values);
    }

    /**
     * Fetch records that have <code>deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchRangeOfDeleted(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(TrackingRecord.TRACKING_RECORD.DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.pluto.millionsExport.jooqData.tables.pojos.TrackingRecord> fetchByDeleted(Byte... values) {
        return fetch(TrackingRecord.TRACKING_RECORD.DELETED, values);
    }
}
