/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data;


import com.pluto.millionsExport.data.tables.Account;
import com.pluto.millionsExport.data.tables.BondAmount;
import com.pluto.millionsExport.data.tables.BondBalanceChange;
import com.pluto.millionsExport.data.tables.BondSizeChg;
import com.pluto.millionsExport.data.tables.BondTicker;
import com.pluto.millionsExport.data.tables.ComGuarInfo;
import com.pluto.millionsExport.data.tables.Good;
import com.pluto.millionsExport.data.tables.Login;
import com.pluto.millionsExport.data.tables.PatientMedicalRecord;
import com.pluto.millionsExport.data.tables.TBondunicodeMapping;
import com.pluto.millionsExport.data.tables.TestCreated;
import com.pluto.millionsExport.data.tables.TrackingRecord;
import com.pluto.millionsExport.data.tables.Trade;
import com.pluto.millionsExport.data.tables.records.AccountRecord;
import com.pluto.millionsExport.data.tables.records.BondAmountRecord;
import com.pluto.millionsExport.data.tables.records.BondBalanceChangeRecord;
import com.pluto.millionsExport.data.tables.records.BondSizeChgRecord;
import com.pluto.millionsExport.data.tables.records.BondTickerRecord;
import com.pluto.millionsExport.data.tables.records.ComGuarInfoRecord;
import com.pluto.millionsExport.data.tables.records.GoodRecord;
import com.pluto.millionsExport.data.tables.records.LoginRecord;
import com.pluto.millionsExport.data.tables.records.PatientMedicalRecordRecord;
import com.pluto.millionsExport.data.tables.records.TBondunicodeMappingRecord;
import com.pluto.millionsExport.data.tables.records.TestCreatedRecord;
import com.pluto.millionsExport.data.tables.records.TrackingRecordRecord;
import com.pluto.millionsExport.data.tables.records.TradeRecord;

import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>learn</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountRecord, Integer> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;
    public static final Identity<BondAmountRecord, Long> IDENTITY_BOND_AMOUNT = Identities0.IDENTITY_BOND_AMOUNT;
    public static final Identity<BondBalanceChangeRecord, ULong> IDENTITY_BOND_BALANCE_CHANGE = Identities0.IDENTITY_BOND_BALANCE_CHANGE;
    public static final Identity<ComGuarInfoRecord, ULong> IDENTITY_COM_GUAR_INFO = Identities0.IDENTITY_COM_GUAR_INFO;
    public static final Identity<GoodRecord, Integer> IDENTITY_GOOD = Identities0.IDENTITY_GOOD;
    public static final Identity<LoginRecord, Integer> IDENTITY_LOGIN = Identities0.IDENTITY_LOGIN;
    public static final Identity<TBondunicodeMappingRecord, Integer> IDENTITY_T_BONDUNICODE_MAPPING = Identities0.IDENTITY_T_BONDUNICODE_MAPPING;
    public static final Identity<TradeRecord, Integer> IDENTITY_TRADE = Identities0.IDENTITY_TRADE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = UniqueKeys0.KEY_ACCOUNT_PRIMARY;
    public static final UniqueKey<BondAmountRecord> KEY_BOND_AMOUNT_PRIMARY = UniqueKeys0.KEY_BOND_AMOUNT_PRIMARY;
    public static final UniqueKey<BondAmountRecord> KEY_BOND_AMOUNT_IDX_ROW_UNIQUE_KEY = UniqueKeys0.KEY_BOND_AMOUNT_IDX_ROW_UNIQUE_KEY;
    public static final UniqueKey<BondBalanceChangeRecord> KEY_BOND_BALANCE_CHANGE_PRIMARY = UniqueKeys0.KEY_BOND_BALANCE_CHANGE_PRIMARY;
    public static final UniqueKey<BondSizeChgRecord> KEY_BOND_SIZE_CHG_PRIMARY = UniqueKeys0.KEY_BOND_SIZE_CHG_PRIMARY;
    public static final UniqueKey<BondTickerRecord> KEY_BOND_TICKER_PRIMARY = UniqueKeys0.KEY_BOND_TICKER_PRIMARY;
    public static final UniqueKey<ComGuarInfoRecord> KEY_COM_GUAR_INFO_PRIMARY = UniqueKeys0.KEY_COM_GUAR_INFO_PRIMARY;
    public static final UniqueKey<ComGuarInfoRecord> KEY_COM_GUAR_INFO_UK_GUAR_INFO = UniqueKeys0.KEY_COM_GUAR_INFO_UK_GUAR_INFO;
    public static final UniqueKey<GoodRecord> KEY_GOOD_PRIMARY = UniqueKeys0.KEY_GOOD_PRIMARY;
    public static final UniqueKey<LoginRecord> KEY_LOGIN_PRIMARY = UniqueKeys0.KEY_LOGIN_PRIMARY;
    public static final UniqueKey<PatientMedicalRecordRecord> KEY_PATIENT_MEDICAL_RECORD_PRIMARY = UniqueKeys0.KEY_PATIENT_MEDICAL_RECORD_PRIMARY;
    public static final UniqueKey<TBondunicodeMappingRecord> KEY_T_BONDUNICODE_MAPPING_PRIMARY = UniqueKeys0.KEY_T_BONDUNICODE_MAPPING_PRIMARY;
    public static final UniqueKey<TBondunicodeMappingRecord> KEY_T_BONDUNICODE_MAPPING_BOND_UNI_CODE = UniqueKeys0.KEY_T_BONDUNICODE_MAPPING_BOND_UNI_CODE;
    public static final UniqueKey<TestCreatedRecord> KEY_TEST_CREATED_PRIMARY = UniqueKeys0.KEY_TEST_CREATED_PRIMARY;
    public static final UniqueKey<TrackingRecordRecord> KEY_TRACKING_RECORD_PRIMARY = UniqueKeys0.KEY_TRACKING_RECORD_PRIMARY;
    public static final UniqueKey<TradeRecord> KEY_TRADE_PRIMARY = UniqueKeys0.KEY_TRADE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountRecord, Integer> IDENTITY_ACCOUNT = Internal.createIdentity(Account.ACCOUNT, Account.ACCOUNT.ID);
        public static Identity<BondAmountRecord, Long> IDENTITY_BOND_AMOUNT = Internal.createIdentity(BondAmount.BOND_AMOUNT, BondAmount.BOND_AMOUNT.ID);
        public static Identity<BondBalanceChangeRecord, ULong> IDENTITY_BOND_BALANCE_CHANGE = Internal.createIdentity(BondBalanceChange.BOND_BALANCE_CHANGE, BondBalanceChange.BOND_BALANCE_CHANGE.ID);
        public static Identity<ComGuarInfoRecord, ULong> IDENTITY_COM_GUAR_INFO = Internal.createIdentity(ComGuarInfo.COM_GUAR_INFO, ComGuarInfo.COM_GUAR_INFO.ID);
        public static Identity<GoodRecord, Integer> IDENTITY_GOOD = Internal.createIdentity(Good.GOOD, Good.GOOD.ID);
        public static Identity<LoginRecord, Integer> IDENTITY_LOGIN = Internal.createIdentity(Login.LOGIN, Login.LOGIN.ID);
        public static Identity<TBondunicodeMappingRecord, Integer> IDENTITY_T_BONDUNICODE_MAPPING = Internal.createIdentity(TBondunicodeMapping.T_BONDUNICODE_MAPPING, TBondunicodeMapping.T_BONDUNICODE_MAPPING.ID);
        public static Identity<TradeRecord, Integer> IDENTITY_TRADE = Internal.createIdentity(Trade.TRADE, Trade.TRADE.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = Internal.createUniqueKey(Account.ACCOUNT, "KEY_account_PRIMARY", new TableField[] { Account.ACCOUNT.ID }, true);
        public static final UniqueKey<BondAmountRecord> KEY_BOND_AMOUNT_PRIMARY = Internal.createUniqueKey(BondAmount.BOND_AMOUNT, "KEY_bond_amount_PRIMARY", new TableField[] { BondAmount.BOND_AMOUNT.ID }, true);
        public static final UniqueKey<BondAmountRecord> KEY_BOND_AMOUNT_IDX_ROW_UNIQUE_KEY = Internal.createUniqueKey(BondAmount.BOND_AMOUNT, "KEY_bond_amount_idx_row_unique_key", new TableField[] { BondAmount.BOND_AMOUNT.ROW_UNIQUE_KEY }, true);
        public static final UniqueKey<BondBalanceChangeRecord> KEY_BOND_BALANCE_CHANGE_PRIMARY = Internal.createUniqueKey(BondBalanceChange.BOND_BALANCE_CHANGE, "KEY_bond_balance_change_PRIMARY", new TableField[] { BondBalanceChange.BOND_BALANCE_CHANGE.ID }, true);
        public static final UniqueKey<BondSizeChgRecord> KEY_BOND_SIZE_CHG_PRIMARY = Internal.createUniqueKey(BondSizeChg.BOND_SIZE_CHG, "KEY_bond_size_chg_PRIMARY", new TableField[] { BondSizeChg.BOND_SIZE_CHG.ID }, true);
        public static final UniqueKey<BondTickerRecord> KEY_BOND_TICKER_PRIMARY = Internal.createUniqueKey(BondTicker.BOND_TICKER, "KEY_bond_ticker_PRIMARY", new TableField[] { BondTicker.BOND_TICKER.ID }, true);
        public static final UniqueKey<ComGuarInfoRecord> KEY_COM_GUAR_INFO_PRIMARY = Internal.createUniqueKey(ComGuarInfo.COM_GUAR_INFO, "KEY_com_guar_info_PRIMARY", new TableField[] { ComGuarInfo.COM_GUAR_INFO.ID }, true);
        public static final UniqueKey<ComGuarInfoRecord> KEY_COM_GUAR_INFO_UK_GUAR_INFO = Internal.createUniqueKey(ComGuarInfo.COM_GUAR_INFO, "KEY_com_guar_info_uk_guar_info", new TableField[] { ComGuarInfo.COM_GUAR_INFO.COM_UNI_CODE, ComGuarInfo.COM_GUAR_INFO.REPORT_YEAR, ComGuarInfo.COM_GUAR_INFO.REPORT_QUARTER, ComGuarInfo.COM_GUAR_INFO.DELETED, ComGuarInfo.COM_GUAR_INFO.PRIVATE_ENTERPRISE_STATUS, ComGuarInfo.COM_GUAR_INFO.OUTSIDE_PROVINCE_STATUS }, true);
        public static final UniqueKey<GoodRecord> KEY_GOOD_PRIMARY = Internal.createUniqueKey(Good.GOOD, "KEY_good_PRIMARY", new TableField[] { Good.GOOD.ID }, true);
        public static final UniqueKey<LoginRecord> KEY_LOGIN_PRIMARY = Internal.createUniqueKey(Login.LOGIN, "KEY_login_PRIMARY", new TableField[] { Login.LOGIN.ID }, true);
        public static final UniqueKey<PatientMedicalRecordRecord> KEY_PATIENT_MEDICAL_RECORD_PRIMARY = Internal.createUniqueKey(PatientMedicalRecord.PATIENT_MEDICAL_RECORD, "KEY_patient_medical_record_PRIMARY", new TableField[] { PatientMedicalRecord.PATIENT_MEDICAL_RECORD.ID }, true);
        public static final UniqueKey<TBondunicodeMappingRecord> KEY_T_BONDUNICODE_MAPPING_PRIMARY = Internal.createUniqueKey(TBondunicodeMapping.T_BONDUNICODE_MAPPING, "KEY_t_bondunicode_mapping_PRIMARY", new TableField[] { TBondunicodeMapping.T_BONDUNICODE_MAPPING.ID }, true);
        public static final UniqueKey<TBondunicodeMappingRecord> KEY_T_BONDUNICODE_MAPPING_BOND_UNI_CODE = Internal.createUniqueKey(TBondunicodeMapping.T_BONDUNICODE_MAPPING, "KEY_t_bondunicode_mapping_bond_uni_code", new TableField[] { TBondunicodeMapping.T_BONDUNICODE_MAPPING.BOND_UNI_CODE }, true);
        public static final UniqueKey<TestCreatedRecord> KEY_TEST_CREATED_PRIMARY = Internal.createUniqueKey(TestCreated.TEST_CREATED, "KEY_test_created_PRIMARY", new TableField[] { TestCreated.TEST_CREATED.ID }, true);
        public static final UniqueKey<TrackingRecordRecord> KEY_TRACKING_RECORD_PRIMARY = Internal.createUniqueKey(TrackingRecord.TRACKING_RECORD, "KEY_tracking_record_PRIMARY", new TableField[] { TrackingRecord.TRACKING_RECORD.ID }, true);
        public static final UniqueKey<TradeRecord> KEY_TRADE_PRIMARY = Internal.createUniqueKey(Trade.TRADE, "KEY_trade_PRIMARY", new TableField[] { Trade.TRADE.ID }, true);
    }
}
