spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: rootroot
