/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables;


import com.pluto.millionsExport.data.Indexes;
import com.pluto.millionsExport.data.Keys;
import com.pluto.millionsExport.data.Learn;
import com.pluto.millionsExport.data.tables.records.TBondunicodeMappingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBondunicodeMapping extends TableImpl<TBondunicodeMappingRecord> {

    private static final long serialVersionUID = -79037572;

    /**
     * The reference instance of <code>learn.t_bondunicode_mapping</code>
     */
    public static final TBondunicodeMapping T_BONDUNICODE_MAPPING = new TBondunicodeMapping();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TBondunicodeMappingRecord> getRecordType() {
        return TBondunicodeMappingRecord.class;
    }

    /**
     * The column <code>learn.t_bondunicode_mapping.id</code>. 主键ID
     */
    public final TableField<TBondunicodeMappingRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "主键ID");

    /**
     * The column <code>learn.t_bondunicode_mapping.bond_uni_code</code>. DM债券code
     */
    public final TableField<TBondunicodeMappingRecord, Long> BOND_UNI_CODE = createField(DSL.name("bond_uni_code"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "DM债券code");

    /**
     * The column <code>learn.t_bondunicode_mapping.bond_code</code>. 带市场的债券社会统一编码
     */
    public final TableField<TBondunicodeMappingRecord, String> BOND_CODE = createField(DSL.name("bond_code"), org.jooq.impl.SQLDataType.VARCHAR(32), this, "带市场的债券社会统一编码");

    /**
     * The column <code>learn.t_bondunicode_mapping.bond_short_name</code>. 债券简称
     */
    public final TableField<TBondunicodeMappingRecord, String> BOND_SHORT_NAME = createField(DSL.name("bond_short_name"), org.jooq.impl.SQLDataType.VARCHAR(128), this, "债券简称");

    /**
     * The column <code>learn.t_bondunicode_mapping.bond_full_name</code>. 债券全称
     */
    public final TableField<TBondunicodeMappingRecord, String> BOND_FULL_NAME = createField(DSL.name("bond_full_name"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "债券全称");

    /**
     * The column <code>learn.t_bondunicode_mapping.ccxe_bond_uni_code</code>. 中诚信债券code
     */
    public final TableField<TBondunicodeMappingRecord, Long> CCXE_BOND_UNI_CODE = createField(DSL.name("ccxe_bond_uni_code"), org.jooq.impl.SQLDataType.BIGINT, this, "中诚信债券code");

    /**
     * The column <code>learn.t_bondunicode_mapping.create_time</code>. 创建时间
     */
    public final TableField<TBondunicodeMappingRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>learn.t_bondunicode_mapping.ch_bond_uni_code</code>. 财汇的债券编号
     */
    public final TableField<TBondunicodeMappingRecord, Long> CH_BOND_UNI_CODE = createField(DSL.name("ch_bond_uni_code"), org.jooq.impl.SQLDataType.BIGINT, this, "财汇的债券编号");

    /**
     * The column <code>learn.t_bondunicode_mapping.is_valid</code>. 是否有效（1：有效 0：无效）
     */
    public final TableField<TBondunicodeMappingRecord, Integer> IS_VALID = createField(DSL.name("is_valid"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "是否有效（1：有效 0：无效）");

    /**
     * The column <code>learn.t_bondunicode_mapping.update_time</code>. 更新时间
     */
    public final TableField<TBondunicodeMappingRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "更新时间");

    /**
     * The column <code>learn.t_bondunicode_mapping.tl_bond_uni_code</code>. 通联债券编码 security_id
     */
    public final TableField<TBondunicodeMappingRecord, Long> TL_BOND_UNI_CODE = createField(DSL.name("tl_bond_uni_code"), org.jooq.impl.SQLDataType.BIGINT, this, "通联债券编码 security_id");

    /**
     * Create a <code>learn.t_bondunicode_mapping</code> table reference
     */
    public TBondunicodeMapping() {
        this(DSL.name("t_bondunicode_mapping"), null);
    }

    /**
     * Create an aliased <code>learn.t_bondunicode_mapping</code> table reference
     */
    public TBondunicodeMapping(String alias) {
        this(DSL.name(alias), T_BONDUNICODE_MAPPING);
    }

    /**
     * Create an aliased <code>learn.t_bondunicode_mapping</code> table reference
     */
    public TBondunicodeMapping(Name alias) {
        this(alias, T_BONDUNICODE_MAPPING);
    }

    private TBondunicodeMapping(Name alias, Table<TBondunicodeMappingRecord> aliased) {
        this(alias, aliased, null);
    }

    private TBondunicodeMapping(Name alias, Table<TBondunicodeMappingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> TBondunicodeMapping(Table<O> child, ForeignKey<O, TBondunicodeMappingRecord> key) {
        super(child, key, T_BONDUNICODE_MAPPING);
    }

    @Override
    public Schema getSchema() {
        return Learn.LEARN;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.T_BONDUNICODE_MAPPING_BOND_CODE, Indexes.T_BONDUNICODE_MAPPING_BOND_FULL_NAME, Indexes.T_BONDUNICODE_MAPPING_BOND_SHORT_NAME, Indexes.T_BONDUNICODE_MAPPING_IDX_CCXE_CODE, Indexes.T_BONDUNICODE_MAPPING_IDX_CH_BOND_UNI_CODE, Indexes.T_BONDUNICODE_MAPPING_IDX_TL_BOND_UNI_CODE);
    }

    @Override
    public Identity<TBondunicodeMappingRecord, Integer> getIdentity() {
        return Keys.IDENTITY_T_BONDUNICODE_MAPPING;
    }

    @Override
    public UniqueKey<TBondunicodeMappingRecord> getPrimaryKey() {
        return Keys.KEY_T_BONDUNICODE_MAPPING_PRIMARY;
    }

    @Override
    public List<UniqueKey<TBondunicodeMappingRecord>> getKeys() {
        return Arrays.<UniqueKey<TBondunicodeMappingRecord>>asList(Keys.KEY_T_BONDUNICODE_MAPPING_PRIMARY, Keys.KEY_T_BONDUNICODE_MAPPING_BOND_UNI_CODE);
    }

    @Override
    public TBondunicodeMapping as(String alias) {
        return new TBondunicodeMapping(DSL.name(alias), this);
    }

    @Override
    public TBondunicodeMapping as(Name alias) {
        return new TBondunicodeMapping(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TBondunicodeMapping rename(String name) {
        return new TBondunicodeMapping(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TBondunicodeMapping rename(Name name) {
        return new TBondunicodeMapping(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Long, String, String, String, Long, LocalDateTime, Long, Integer, LocalDateTime, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
