/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements Serializable {

    private static final long serialVersionUID = -1902197145;

    private Integer id;
    private String  name;
    private Integer age;
    private String  phone;
    private String  address;
    private Byte    disable;

    public Account() {}

    public Account(Account value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.phone = value.phone;
        this.address = value.address;
        this.disable = value.disable;
    }

    public Account(
        Integer id,
        String  name,
        Integer age,
        String  phone,
        String  address,
        Byte    disable
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.phone = phone;
        this.address = address;
        this.disable = disable;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Byte getDisable() {
        return this.disable;
    }

    public void setDisable(Byte disable) {
        this.disable = disable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(phone);
        sb.append(", ").append(address);
        sb.append(", ").append(disable);

        sb.append(")");
        return sb.toString();
    }
}
