/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * 债券余额数据表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BondAmount implements Serializable {

    private static final long serialVersionUID = 892204740;

    private Long          id;
    private Long          bondUniCode;
    private LocalDate     publishDate;
    private LocalDate     changeDate;
    private Byte          changeReason;
    private BigDecimal    changeAmount;
    private BigDecimal    remainAmount;
    private Byte          validStatus;
    private Long          updateBy;
    private LocalDateTime updateTime;
    private LocalDateTime createTime;
    private String        rowUniqueKey;

    public BondAmount() {}

    public BondAmount(BondAmount value) {
        this.id = value.id;
        this.bondUniCode = value.bondUniCode;
        this.publishDate = value.publishDate;
        this.changeDate = value.changeDate;
        this.changeReason = value.changeReason;
        this.changeAmount = value.changeAmount;
        this.remainAmount = value.remainAmount;
        this.validStatus = value.validStatus;
        this.updateBy = value.updateBy;
        this.updateTime = value.updateTime;
        this.createTime = value.createTime;
        this.rowUniqueKey = value.rowUniqueKey;
    }

    public BondAmount(
        Long          id,
        Long          bondUniCode,
        LocalDate     publishDate,
        LocalDate     changeDate,
        Byte          changeReason,
        BigDecimal    changeAmount,
        BigDecimal    remainAmount,
        Byte          validStatus,
        Long          updateBy,
        LocalDateTime updateTime,
        LocalDateTime createTime,
        String        rowUniqueKey
    ) {
        this.id = id;
        this.bondUniCode = bondUniCode;
        this.publishDate = publishDate;
        this.changeDate = changeDate;
        this.changeReason = changeReason;
        this.changeAmount = changeAmount;
        this.remainAmount = remainAmount;
        this.validStatus = validStatus;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.rowUniqueKey = rowUniqueKey;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBondUniCode() {
        return this.bondUniCode;
    }

    public void setBondUniCode(Long bondUniCode) {
        this.bondUniCode = bondUniCode;
    }

    public LocalDate getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(LocalDate publishDate) {
        this.publishDate = publishDate;
    }

    public LocalDate getChangeDate() {
        return this.changeDate;
    }

    public void setChangeDate(LocalDate changeDate) {
        this.changeDate = changeDate;
    }

    public Byte getChangeReason() {
        return this.changeReason;
    }

    public void setChangeReason(Byte changeReason) {
        this.changeReason = changeReason;
    }

    public BigDecimal getChangeAmount() {
        return this.changeAmount;
    }

    public void setChangeAmount(BigDecimal changeAmount) {
        this.changeAmount = changeAmount;
    }

    public BigDecimal getRemainAmount() {
        return this.remainAmount;
    }

    public void setRemainAmount(BigDecimal remainAmount) {
        this.remainAmount = remainAmount;
    }

    public Byte getValidStatus() {
        return this.validStatus;
    }

    public void setValidStatus(Byte validStatus) {
        this.validStatus = validStatus;
    }

    public Long getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(Long updateBy) {
        this.updateBy = updateBy;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getRowUniqueKey() {
        return this.rowUniqueKey;
    }

    public void setRowUniqueKey(String rowUniqueKey) {
        this.rowUniqueKey = rowUniqueKey;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BondAmount (");

        sb.append(id);
        sb.append(", ").append(bondUniCode);
        sb.append(", ").append(publishDate);
        sb.append(", ").append(changeDate);
        sb.append(", ").append(changeReason);
        sb.append(", ").append(changeAmount);
        sb.append(", ").append(remainAmount);
        sb.append(", ").append(validStatus);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(rowUniqueKey);

        sb.append(")");
        return sb.toString();
    }
}
