/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Course implements Serializable {

    private static final long serialVersionUID = 1537977649;

    private Integer cId;
    private String  cname;
    private Integer tId;

    public Course() {}

    public Course(Course value) {
        this.cId = value.cId;
        this.cname = value.cname;
        this.tId = value.tId;
    }

    public Course(
        Integer cId,
        String  cname,
        Integer tId
    ) {
        this.cId = cId;
        this.cname = cname;
        this.tId = tId;
    }

    public Integer getCId() {
        return this.cId;
    }

    public void setCId(Integer cId) {
        this.cId = cId;
    }

    public String getCname() {
        return this.cname;
    }

    public void setCname(String cname) {
        this.cname = cname;
    }

    public Integer getTId() {
        return this.tId;
    }

    public void setTId(Integer tId) {
        this.tId = tId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Course (");

        sb.append(cId);
        sb.append(", ").append(cname);
        sb.append(", ").append(tId);

        sb.append(")");
        return sb.toString();
    }
}
