/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TBondunicodeMapping implements Serializable {

    private static final long serialVersionUID = -582989298;

    private Integer       id;
    private Long          bondUniCode;
    private String        bondCode;
    private String        bondShortName;
    private String        bondFullName;
    private Long          ccxeBondUniCode;
    private LocalDateTime createTime;
    private Long          chBondUniCode;
    private Integer       isValid;
    private LocalDateTime updateTime;
    private Long          tlBondUniCode;

    public TBondunicodeMapping() {}

    public TBondunicodeMapping(TBondunicodeMapping value) {
        this.id = value.id;
        this.bondUniCode = value.bondUniCode;
        this.bondCode = value.bondCode;
        this.bondShortName = value.bondShortName;
        this.bondFullName = value.bondFullName;
        this.ccxeBondUniCode = value.ccxeBondUniCode;
        this.createTime = value.createTime;
        this.chBondUniCode = value.chBondUniCode;
        this.isValid = value.isValid;
        this.updateTime = value.updateTime;
        this.tlBondUniCode = value.tlBondUniCode;
    }

    public TBondunicodeMapping(
        Integer       id,
        Long          bondUniCode,
        String        bondCode,
        String        bondShortName,
        String        bondFullName,
        Long          ccxeBondUniCode,
        LocalDateTime createTime,
        Long          chBondUniCode,
        Integer       isValid,
        LocalDateTime updateTime,
        Long          tlBondUniCode
    ) {
        this.id = id;
        this.bondUniCode = bondUniCode;
        this.bondCode = bondCode;
        this.bondShortName = bondShortName;
        this.bondFullName = bondFullName;
        this.ccxeBondUniCode = ccxeBondUniCode;
        this.createTime = createTime;
        this.chBondUniCode = chBondUniCode;
        this.isValid = isValid;
        this.updateTime = updateTime;
        this.tlBondUniCode = tlBondUniCode;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getBondUniCode() {
        return this.bondUniCode;
    }

    public void setBondUniCode(Long bondUniCode) {
        this.bondUniCode = bondUniCode;
    }

    public String getBondCode() {
        return this.bondCode;
    }

    public void setBondCode(String bondCode) {
        this.bondCode = bondCode;
    }

    public String getBondShortName() {
        return this.bondShortName;
    }

    public void setBondShortName(String bondShortName) {
        this.bondShortName = bondShortName;
    }

    public String getBondFullName() {
        return this.bondFullName;
    }

    public void setBondFullName(String bondFullName) {
        this.bondFullName = bondFullName;
    }

    public Long getCcxeBondUniCode() {
        return this.ccxeBondUniCode;
    }

    public void setCcxeBondUniCode(Long ccxeBondUniCode) {
        this.ccxeBondUniCode = ccxeBondUniCode;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public Long getChBondUniCode() {
        return this.chBondUniCode;
    }

    public void setChBondUniCode(Long chBondUniCode) {
        this.chBondUniCode = chBondUniCode;
    }

    public Integer getIsValid() {
        return this.isValid;
    }

    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Long getTlBondUniCode() {
        return this.tlBondUniCode;
    }

    public void setTlBondUniCode(Long tlBondUniCode) {
        this.tlBondUniCode = tlBondUniCode;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TBondunicodeMapping (");

        sb.append(id);
        sb.append(", ").append(bondUniCode);
        sb.append(", ").append(bondCode);
        sb.append(", ").append(bondShortName);
        sb.append(", ").append(bondFullName);
        sb.append(", ").append(ccxeBondUniCode);
        sb.append(", ").append(createTime);
        sb.append(", ").append(chBondUniCode);
        sb.append(", ").append(isValid);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(tlBondUniCode);

        sb.append(")");
        return sb.toString();
    }
}
