/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 埋点记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackingRecord implements Serializable {

    private static final long serialVersionUID = -1937607324;

    private String        id;
    private String        trackingId;
    private String        userId;
    private String        openId;
    private String        patientId;
    private String        physicianId;
    private String        eventType;
    private String        createBy;
    private LocalDateTime createTime;
    private String        updateBy;
    private LocalDateTime updateTime;
    private Integer       revision;
    private Byte          deleted;

    public TrackingRecord() {}

    public TrackingRecord(TrackingRecord value) {
        this.id = value.id;
        this.trackingId = value.trackingId;
        this.userId = value.userId;
        this.openId = value.openId;
        this.patientId = value.patientId;
        this.physicianId = value.physicianId;
        this.eventType = value.eventType;
        this.createBy = value.createBy;
        this.createTime = value.createTime;
        this.updateBy = value.updateBy;
        this.updateTime = value.updateTime;
        this.revision = value.revision;
        this.deleted = value.deleted;
    }

    public TrackingRecord(
        String        id,
        String        trackingId,
        String        userId,
        String        openId,
        String        patientId,
        String        physicianId,
        String        eventType,
        String        createBy,
        LocalDateTime createTime,
        String        updateBy,
        LocalDateTime updateTime,
        Integer       revision,
        Byte          deleted
    ) {
        this.id = id;
        this.trackingId = trackingId;
        this.userId = userId;
        this.openId = openId;
        this.patientId = patientId;
        this.physicianId = physicianId;
        this.eventType = eventType;
        this.createBy = createBy;
        this.createTime = createTime;
        this.updateBy = updateBy;
        this.updateTime = updateTime;
        this.revision = revision;
        this.deleted = deleted;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTrackingId() {
        return this.trackingId;
    }

    public void setTrackingId(String trackingId) {
        this.trackingId = trackingId;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getPatientId() {
        return this.patientId;
    }

    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    public String getPhysicianId() {
        return this.physicianId;
    }

    public void setPhysicianId(String physicianId) {
        this.physicianId = physicianId;
    }

    public String getEventType() {
        return this.eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getRevision() {
        return this.revision;
    }

    public void setRevision(Integer revision) {
        this.revision = revision;
    }

    public Byte getDeleted() {
        return this.deleted;
    }

    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TrackingRecord (");

        sb.append(id);
        sb.append(", ").append(trackingId);
        sb.append(", ").append(userId);
        sb.append(", ").append(openId);
        sb.append(", ").append(patientId);
        sb.append(", ").append(physicianId);
        sb.append(", ").append(eventType);
        sb.append(", ").append(createBy);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(revision);
        sb.append(", ").append(deleted);

        sb.append(")");
        return sb.toString();
    }
}
