/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Trade implements Serializable {

    private static final long serialVersionUID = 1834563121;

    private Integer       id;
    private String        goodSn;
    private BigDecimal    reelPrice;
    private String        operate;
    private LocalDateTime created;
    private LocalDateTime updated;

    public Trade() {}

    public Trade(Trade value) {
        this.id = value.id;
        this.goodSn = value.goodSn;
        this.reelPrice = value.reelPrice;
        this.operate = value.operate;
        this.created = value.created;
        this.updated = value.updated;
    }

    public Trade(
        Integer       id,
        String        goodSn,
        BigDecimal    reelPrice,
        String        operate,
        LocalDateTime created,
        LocalDateTime updated
    ) {
        this.id = id;
        this.goodSn = goodSn;
        this.reelPrice = reelPrice;
        this.operate = operate;
        this.created = created;
        this.updated = updated;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGoodSn() {
        return this.goodSn;
    }

    public void setGoodSn(String goodSn) {
        this.goodSn = goodSn;
    }

    public BigDecimal getReelPrice() {
        return this.reelPrice;
    }

    public void setReelPrice(BigDecimal reelPrice) {
        this.reelPrice = reelPrice;
    }

    public String getOperate() {
        return this.operate;
    }

    public void setOperate(String operate) {
        this.operate = operate;
    }

    public LocalDateTime getCreated() {
        return this.created;
    }

    public void setCreated(LocalDateTime created) {
        this.created = created;
    }

    public LocalDateTime getUpdated() {
        return this.updated;
    }

    public void setUpdated(LocalDateTime updated) {
        this.updated = updated;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Trade (");

        sb.append(id);
        sb.append(", ").append(goodSn);
        sb.append(", ").append(reelPrice);
        sb.append(", ").append(operate);
        sb.append(", ").append(created);
        sb.append(", ").append(updated);

        sb.append(")");
        return sb.toString();
    }
}
