/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.daos;


import com.pluto.millionsExport.data.tables.BondTicker;
import com.pluto.millionsExport.data.tables.records.BondTickerRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BondTickerDao extends DAOImpl<BondTickerRecord, com.pluto.millionsExport.data.tables.pojos.BondTicker, Long> {

    /**
     * Create a new BondTickerDao without any configuration
     */
    public BondTickerDao() {
        super(BondTicker.BOND_TICKER, com.pluto.millionsExport.data.tables.pojos.BondTicker.class);
    }

    /**
     * Create a new BondTickerDao with an attached configuration
     */
    public BondTickerDao(Configuration configuration) {
        super(BondTicker.BOND_TICKER, com.pluto.millionsExport.data.tables.pojos.BondTicker.class, configuration);
    }

    @Override
    public Long getId(com.pluto.millionsExport.data.tables.pojos.BondTicker object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondTicker.BOND_TICKER.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchById(Long... values) {
        return fetch(BondTicker.BOND_TICKER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.pluto.millionsExport.data.tables.pojos.BondTicker fetchOneById(Long value) {
        return fetchOne(BondTicker.BOND_TICKER.ID, value);
    }

    /**
     * Fetch records that have <code>BOND_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchRangeOfBondId(String lowerInclusive, String upperInclusive) {
        return fetchRange(BondTicker.BOND_TICKER.BOND_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>BOND_ID IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchByBondId(String... values) {
        return fetch(BondTicker.BOND_TICKER.BOND_ID, values);
    }

    /**
     * Fetch records that have <code>SECURITY_ID BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchRangeOfSecurityId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondTicker.BOND_TICKER.SECURITY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>SECURITY_ID IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchBySecurityId(Long... values) {
        return fetch(BondTicker.BOND_TICKER.SECURITY_ID, values);
    }

    /**
     * Fetch records that have <code>UPDATE_TIME BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(BondTicker.BOND_TICKER.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>UPDATE_TIME IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(BondTicker.BOND_TICKER.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>TMSTAMP BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchRangeOfTmstamp(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondTicker.BOND_TICKER.TMSTAMP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>TMSTAMP IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondTicker> fetchByTmstamp(Long... values) {
        return fetch(BondTicker.BOND_TICKER.TMSTAMP, values);
    }
}
