/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.daos;


import com.pluto.millionsExport.data.tables.BondAmount;
import com.pluto.millionsExport.data.tables.records.BondAmountRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 债券余额数据表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BondAmountDao extends DAOImpl<BondAmountRecord, com.pluto.millionsExport.data.tables.pojos.BondAmount, Long> {

    /**
     * Create a new BondAmountDao without any configuration
     */
    public BondAmountDao() {
        super(BondAmount.BOND_AMOUNT, com.pluto.millionsExport.data.tables.pojos.BondAmount.class);
    }

    /**
     * Create a new BondAmountDao with an attached configuration
     */
    public BondAmountDao(Configuration configuration) {
        super(BondAmount.BOND_AMOUNT, com.pluto.millionsExport.data.tables.pojos.BondAmount.class, configuration);
    }

    @Override
    public Long getId(com.pluto.millionsExport.data.tables.pojos.BondAmount object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchById(Long... values) {
        return fetch(BondAmount.BOND_AMOUNT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pluto.millionsExport.data.tables.pojos.BondAmount fetchOneById(Long value) {
        return fetchOne(BondAmount.BOND_AMOUNT.ID, value);
    }

    /**
     * Fetch records that have <code>bond_uni_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfBondUniCode(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.BOND_UNI_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bond_uni_code IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByBondUniCode(Long... values) {
        return fetch(BondAmount.BOND_AMOUNT.BOND_UNI_CODE, values);
    }

    /**
     * Fetch records that have <code>publish_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfPublishDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.PUBLISH_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>publish_date IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByPublishDate(LocalDate... values) {
        return fetch(BondAmount.BOND_AMOUNT.PUBLISH_DATE, values);
    }

    /**
     * Fetch records that have <code>change_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfChangeDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.CHANGE_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>change_date IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByChangeDate(LocalDate... values) {
        return fetch(BondAmount.BOND_AMOUNT.CHANGE_DATE, values);
    }

    /**
     * Fetch records that have <code>change_reason BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfChangeReason(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.CHANGE_REASON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>change_reason IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByChangeReason(Byte... values) {
        return fetch(BondAmount.BOND_AMOUNT.CHANGE_REASON, values);
    }

    /**
     * Fetch records that have <code>change_amount BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfChangeAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.CHANGE_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>change_amount IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByChangeAmount(BigDecimal... values) {
        return fetch(BondAmount.BOND_AMOUNT.CHANGE_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>remain_amount BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfRemainAmount(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.REMAIN_AMOUNT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>remain_amount IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByRemainAmount(BigDecimal... values) {
        return fetch(BondAmount.BOND_AMOUNT.REMAIN_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>valid_status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfValidStatus(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.VALID_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>valid_status IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByValidStatus(Byte... values) {
        return fetch(BondAmount.BOND_AMOUNT.VALID_STATUS, values);
    }

    /**
     * Fetch records that have <code>update_by BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfUpdateBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.UPDATE_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_by IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByUpdateBy(Long... values) {
        return fetch(BondAmount.BOND_AMOUNT.UPDATE_BY, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(BondAmount.BOND_AMOUNT.UPDATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByCreateTime(LocalDateTime... values) {
        return fetch(BondAmount.BOND_AMOUNT.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>row_unique_key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchRangeOfRowUniqueKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(BondAmount.BOND_AMOUNT.ROW_UNIQUE_KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>row_unique_key IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.BondAmount> fetchByRowUniqueKey(String... values) {
        return fetch(BondAmount.BOND_AMOUNT.ROW_UNIQUE_KEY, values);
    }

    /**
     * Fetch a unique record that has <code>row_unique_key = value</code>
     */
    public com.pluto.millionsExport.data.tables.pojos.BondAmount fetchOneByRowUniqueKey(String value) {
        return fetchOne(BondAmount.BOND_AMOUNT.ROW_UNIQUE_KEY, value);
    }
}
