/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.data.tables.daos;


import com.pluto.millionsExport.data.tables.ComGuarInfo;
import com.pluto.millionsExport.data.tables.records.ComGuarInfoRecord;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * 公司担保基本信息
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComGuarInfoDao extends DAOImpl<ComGuarInfoRecord, com.pluto.millionsExport.data.tables.pojos.ComGuarInfo, ULong> {

    /**
     * Create a new ComGuarInfoDao without any configuration
     */
    public ComGuarInfoDao() {
        super(ComGuarInfo.COM_GUAR_INFO, com.pluto.millionsExport.data.tables.pojos.ComGuarInfo.class);
    }

    /**
     * Create a new ComGuarInfoDao with an attached configuration
     */
    public ComGuarInfoDao(Configuration configuration) {
        super(ComGuarInfo.COM_GUAR_INFO, com.pluto.millionsExport.data.tables.pojos.ComGuarInfo.class, configuration);
    }

    @Override
    public ULong getId(com.pluto.millionsExport.data.tables.pojos.ComGuarInfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchById(ULong... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.pluto.millionsExport.data.tables.pojos.ComGuarInfo fetchOneById(ULong value) {
        return fetchOne(ComGuarInfo.COM_GUAR_INFO.ID, value);
    }

    /**
     * Fetch records that have <code>com_uni_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfComUniCode(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.COM_UNI_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>com_uni_code IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByComUniCode(Long... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.COM_UNI_CODE, values);
    }

    /**
     * Fetch records that have <code>com_full_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfComFullName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.COM_FULL_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>com_full_name IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByComFullName(String... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.COM_FULL_NAME, values);
    }

    /**
     * Fetch records that have <code>report_year BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfReportYear(Short lowerInclusive, Short upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.REPORT_YEAR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_year IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByReportYear(Short... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.REPORT_YEAR, values);
    }

    /**
     * Fetch records that have <code>report_quarter BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfReportQuarter(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.REPORT_QUARTER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_quarter IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByReportQuarter(Byte... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.REPORT_QUARTER, values);
    }

    /**
     * Fetch records that have <code>guarantee_bond_number BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfGuaranteeBondNumber(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.GUARANTEE_BOND_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>guarantee_bond_number IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByGuaranteeBondNumber(Integer... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.GUARANTEE_BOND_NUMBER, values);
    }

    /**
     * Fetch records that have <code>guarantee_bp BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfGuaranteeBp(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.GUARANTEE_BP, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>guarantee_bp IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByGuaranteeBp(BigDecimal... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.GUARANTEE_BP, values);
    }

    /**
     * Fetch records that have <code>bond_coupon_rate_avg BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfBondCouponRateAvg(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.BOND_COUPON_RATE_AVG, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>bond_coupon_rate_avg IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByBondCouponRateAvg(BigDecimal... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.BOND_COUPON_RATE_AVG, values);
    }

    /**
     * Fetch records that have <code>guar_liability_balance_gr BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfGuarLiabilityBalanceGr(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.GUAR_LIABILITY_BALANCE_GR, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>guar_liability_balance_gr IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByGuarLiabilityBalanceGr(BigDecimal... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.GUAR_LIABILITY_BALANCE_GR, values);
    }

    /**
     * Fetch records that have <code>udic_radio BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfUdicRadio(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.UDIC_RADIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>udic_radio IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByUdicRadio(BigDecimal... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.UDIC_RADIO, values);
    }

    /**
     * Fetch records that have <code>private_enterprise_ratio BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfPrivateEnterpriseRatio(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.PRIVATE_ENTERPRISE_RATIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>private_enterprise_ratio IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByPrivateEnterpriseRatio(BigDecimal... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.PRIVATE_ENTERPRISE_RATIO, values);
    }

    /**
     * Fetch records that have <code>outside_province_ratio BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfOutsideProvinceRatio(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.OUTSIDE_PROVINCE_RATIO, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>outside_province_ratio IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByOutsideProvinceRatio(BigDecimal... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.OUTSIDE_PROVINCE_RATIO, values);
    }

    /**
     * Fetch records that have <code>private_enterprise_status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfPrivateEnterpriseStatus(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.PRIVATE_ENTERPRISE_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>private_enterprise_status IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByPrivateEnterpriseStatus(UByte... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.PRIVATE_ENTERPRISE_STATUS, values);
    }

    /**
     * Fetch records that have <code>outside_province_status BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfOutsideProvinceStatus(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.OUTSIDE_PROVINCE_STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>outside_province_status IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByOutsideProvinceStatus(UByte... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.OUTSIDE_PROVINCE_STATUS, values);
    }

    /**
     * Fetch records that have <code>province_uni_code BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfProvinceUniCode(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.PROVINCE_UNI_CODE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>province_uni_code IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByProvinceUniCode(ULong... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.PROVINCE_UNI_CODE, values);
    }

    /**
     * Fetch records that have <code>com_current_bonds_balance BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfComCurrentBondsBalance(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.COM_CURRENT_BONDS_BALANCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>com_current_bonds_balance IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByComCurrentBondsBalance(BigDecimal... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.COM_CURRENT_BONDS_BALANCE, values);
    }

    /**
     * Fetch records that have <code>com_ext_rating_filter_mapping BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfComExtRatingFilterMapping(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.COM_EXT_RATING_FILTER_MAPPING, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>com_ext_rating_filter_mapping IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByComExtRatingFilterMapping(UShort... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.COM_EXT_RATING_FILTER_MAPPING, values);
    }

    /**
     * Fetch records that have <code>com_ext_credit_rating_com_name BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfComExtCreditRatingComName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.COM_EXT_CREDIT_RATING_COM_NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>com_ext_credit_rating_com_name IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByComExtCreditRatingComName(String... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.COM_EXT_CREDIT_RATING_COM_NAME, values);
    }

    /**
     * Fetch records that have <code>establish_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfEstablishDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.ESTABLISH_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>establish_date IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByEstablishDate(LocalDate... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.ESTABLISH_DATE, values);
    }

    /**
     * Fetch records that have <code>deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfDeleted(Byte lowerInclusive, Byte upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deleted IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByDeleted(Byte... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.DELETED, values);
    }

    /**
     * Fetch records that have <code>registered_capital BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfRegisteredCapital(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.REGISTERED_CAPITAL, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>registered_capital IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByRegisteredCapital(Long... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.REGISTERED_CAPITAL, values);
    }

    /**
     * Fetch records that have <code>business_nature BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfBusinessNature(UShort lowerInclusive, UShort upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.BUSINESS_NATURE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>business_nature IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByBusinessNature(UShort... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.BUSINESS_NATURE, values);
    }

    /**
     * Fetch records that have <code>report_date BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchRangeOfReportDate(LocalDate lowerInclusive, LocalDate upperInclusive) {
        return fetchRange(ComGuarInfo.COM_GUAR_INFO.REPORT_DATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_date IN (values)</code>
     */
    public List<com.pluto.millionsExport.data.tables.pojos.ComGuarInfo> fetchByReportDate(LocalDate... values) {
        return fetch(ComGuarInfo.COM_GUAR_INFO.REPORT_DATE, values);
    }
}
