/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData;


/**
 * A class modelling indexes of tables of the <code>learn</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {

    }
}
