/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData;


import com.pluto.millionsExport.jooqData.tables.MillionsData;
import com.pluto.millionsExport.jooqData.tables.records.MillionsDataRecord;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>learn</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MillionsDataRecord, Integer> IDENTITY_MILLIONS_DATA = Identities0.IDENTITY_MILLIONS_DATA;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MillionsDataRecord> KEY_MILLIONS_DATA_PRIMARY = UniqueKeys0.KEY_MILLIONS_DATA_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<MillionsDataRecord, Integer> IDENTITY_MILLIONS_DATA = Internal.createIdentity(MillionsData.MILLIONS_DATA, MillionsData.MILLIONS_DATA.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<MillionsDataRecord> KEY_MILLIONS_DATA_PRIMARY = Internal.createUniqueKey(MillionsData.MILLIONS_DATA, "KEY_millions_data_PRIMARY", new TableField[] { MillionsData.MILLIONS_DATA.ID }, true);
    }
}
