/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData;


import com.pluto.millionsExport.jooqData.tables.Account;
import com.pluto.millionsExport.jooqData.tables.BondAmount;
import com.pluto.millionsExport.jooqData.tables.BondBalanceChange;
import com.pluto.millionsExport.jooqData.tables.BondSizeChg;
import com.pluto.millionsExport.jooqData.tables.BondTicker;
import com.pluto.millionsExport.jooqData.tables.ComGuarInfo;
import com.pluto.millionsExport.jooqData.tables.Course;
import com.pluto.millionsExport.jooqData.tables.Good;
import com.pluto.millionsExport.jooqData.tables.Login;
import com.pluto.millionsExport.jooqData.tables.MillionsData;
import com.pluto.millionsExport.jooqData.tables.ParseTemplate;
import com.pluto.millionsExport.jooqData.tables.PatientMedicalRecord;
import com.pluto.millionsExport.jooqData.tables.Student;
import com.pluto.millionsExport.jooqData.tables.TBondunicodeMapping;
import com.pluto.millionsExport.jooqData.tables.TestCreated;
import com.pluto.millionsExport.jooqData.tables.TrackingRecord;
import com.pluto.millionsExport.jooqData.tables.Trade;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Learn extends SchemaImpl {

    private static final long serialVersionUID = 1561012647;

    /**
     * The reference instance of <code>learn</code>
     */
    public static final Learn LEARN = new Learn();

    /**
     * The table <code>learn.account</code>.
     */
    public final Account ACCOUNT = Account.ACCOUNT;

    /**
     * 债券余额数据表
     */
    public final BondAmount BOND_AMOUNT = BondAmount.BOND_AMOUNT;

    /**
     * 债券余额数据表
     */
    public final BondBalanceChange BOND_BALANCE_CHANGE = BondBalanceChange.BOND_BALANCE_CHANGE;

    /**
     * The table <code>learn.bond_size_chg</code>.
     */
    public final BondSizeChg BOND_SIZE_CHG = BondSizeChg.BOND_SIZE_CHG;

    /**
     * The table <code>learn.bond_ticker</code>.
     */
    public final BondTicker BOND_TICKER = BondTicker.BOND_TICKER;

    /**
     * 公司担保基本信息
     */
    public final ComGuarInfo COM_GUAR_INFO = ComGuarInfo.COM_GUAR_INFO;

    /**
     * The table <code>learn.course</code>.
     */
    public final Course COURSE = Course.COURSE;

    /**
     * The table <code>learn.good</code>.
     */
    public final Good GOOD = Good.GOOD;

    /**
     * The table <code>learn.login</code>.
     */
    public final Login LOGIN = Login.LOGIN;

    /**
     * 百万数据导入导出测试
     */
    public final MillionsData MILLIONS_DATA = MillionsData.MILLIONS_DATA;

    /**
     * The table <code>learn.parse_template</code>.
     */
    public final ParseTemplate PARSE_TEMPLATE = ParseTemplate.PARSE_TEMPLATE;

    /**
     * 患者结构化病历病程表
     */
    public final PatientMedicalRecord PATIENT_MEDICAL_RECORD = PatientMedicalRecord.PATIENT_MEDICAL_RECORD;

    /**
     * The table <code>learn.student</code>.
     */
    public final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>learn.t_bondunicode_mapping</code>.
     */
    public final TBondunicodeMapping T_BONDUNICODE_MAPPING = TBondunicodeMapping.T_BONDUNICODE_MAPPING;

    /**
     * 测试创建库
     */
    public final TestCreated TEST_CREATED = TestCreated.TEST_CREATED;

    /**
     * 埋点记录表
     */
    public final TrackingRecord TRACKING_RECORD = TrackingRecord.TRACKING_RECORD;

    /**
     * The table <code>learn.trade</code>.
     */
    public final Trade TRADE = Trade.TRADE;

    /**
     * No further instances allowed
     */
    private Learn() {
        super("learn", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            BondAmount.BOND_AMOUNT,
            BondBalanceChange.BOND_BALANCE_CHANGE,
            BondSizeChg.BOND_SIZE_CHG,
            BondTicker.BOND_TICKER,
            ComGuarInfo.COM_GUAR_INFO,
            Course.COURSE,
            Good.GOOD,
            Login.LOGIN,
            MillionsData.MILLIONS_DATA,
            ParseTemplate.PARSE_TEMPLATE,
            PatientMedicalRecord.PATIENT_MEDICAL_RECORD,
            Student.STUDENT,
            TBondunicodeMapping.T_BONDUNICODE_MAPPING,
            TestCreated.TEST_CREATED,
            TrackingRecord.TRACKING_RECORD,
            Trade.TRADE);
    }
}
