/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData;


import com.pluto.millionsExport.jooqData.tables.Account;
import com.pluto.millionsExport.jooqData.tables.BondAmount;
import com.pluto.millionsExport.jooqData.tables.BondBalanceChange;
import com.pluto.millionsExport.jooqData.tables.BondSizeChg;
import com.pluto.millionsExport.jooqData.tables.BondTicker;
import com.pluto.millionsExport.jooqData.tables.ComGuarInfo;
import com.pluto.millionsExport.jooqData.tables.Course;
import com.pluto.millionsExport.jooqData.tables.Good;
import com.pluto.millionsExport.jooqData.tables.Login;
import com.pluto.millionsExport.jooqData.tables.MillionsData;
import com.pluto.millionsExport.jooqData.tables.ParseTemplate;
import com.pluto.millionsExport.jooqData.tables.PatientMedicalRecord;
import com.pluto.millionsExport.jooqData.tables.Student;
import com.pluto.millionsExport.jooqData.tables.TBondunicodeMapping;
import com.pluto.millionsExport.jooqData.tables.TestCreated;
import com.pluto.millionsExport.jooqData.tables.TrackingRecord;
import com.pluto.millionsExport.jooqData.tables.Trade;


/**
 * Convenience access to all tables in learn
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>learn.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * 债券余额数据表
     */
    public static final BondAmount BOND_AMOUNT = BondAmount.BOND_AMOUNT;

    /**
     * 债券余额数据表
     */
    public static final BondBalanceChange BOND_BALANCE_CHANGE = BondBalanceChange.BOND_BALANCE_CHANGE;

    /**
     * The table <code>learn.bond_size_chg</code>.
     */
    public static final BondSizeChg BOND_SIZE_CHG = BondSizeChg.BOND_SIZE_CHG;

    /**
     * The table <code>learn.bond_ticker</code>.
     */
    public static final BondTicker BOND_TICKER = BondTicker.BOND_TICKER;

    /**
     * 公司担保基本信息
     */
    public static final ComGuarInfo COM_GUAR_INFO = ComGuarInfo.COM_GUAR_INFO;

    /**
     * The table <code>learn.course</code>.
     */
    public static final Course COURSE = Course.COURSE;

    /**
     * The table <code>learn.good</code>.
     */
    public static final Good GOOD = Good.GOOD;

    /**
     * The table <code>learn.login</code>.
     */
    public static final Login LOGIN = Login.LOGIN;

    /**
     * 百万数据导入导出测试
     */
    public static final MillionsData MILLIONS_DATA = MillionsData.MILLIONS_DATA;

    /**
     * The table <code>learn.parse_template</code>.
     */
    public static final ParseTemplate PARSE_TEMPLATE = ParseTemplate.PARSE_TEMPLATE;

    /**
     * 患者结构化病历病程表
     */
    public static final PatientMedicalRecord PATIENT_MEDICAL_RECORD = PatientMedicalRecord.PATIENT_MEDICAL_RECORD;

    /**
     * The table <code>learn.student</code>.
     */
    public static final Student STUDENT = Student.STUDENT;

    /**
     * The table <code>learn.t_bondunicode_mapping</code>.
     */
    public static final TBondunicodeMapping T_BONDUNICODE_MAPPING = TBondunicodeMapping.T_BONDUNICODE_MAPPING;

    /**
     * 测试创建库
     */
    public static final TestCreated TEST_CREATED = TestCreated.TEST_CREATED;

    /**
     * 埋点记录表
     */
    public static final TrackingRecord TRACKING_RECORD = TrackingRecord.TRACKING_RECORD;

    /**
     * The table <code>learn.trade</code>.
     */
    public static final Trade TRADE = Trade.TRADE;
}
