/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.records;


import com.pluto.millionsExport.jooqData.tables.MillionsData;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 百万数据导入导出测试
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MillionsDataRecord extends UpdatableRecordImpl<MillionsDataRecord> implements Record5<Integer, Long, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1549848785;

    /**
     * Setter for <code>learn.millions_data.id</code>. 主键
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>learn.millions_data.id</code>. 主键
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>learn.millions_data.staff_no</code>. 员工号
     */
    public void setStaffNo(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>learn.millions_data.staff_no</code>. 员工号
     */
    public Long getStaffNo() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>learn.millions_data.salary</code>. 薪水
     */
    public void setSalary(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>learn.millions_data.salary</code>. 薪水
     */
    public BigDecimal getSalary() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>learn.millions_data.start_time</code>. 开始时间
     */
    public void setStartTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>learn.millions_data.start_time</code>. 开始时间
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>learn.millions_data.end_time</code>. 结束时间
     */
    public void setEndTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>learn.millions_data.end_time</code>. 结束时间
     */
    public LocalDateTime getEndTime() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Long, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Long, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return MillionsData.MILLIONS_DATA.ID;
    }

    @Override
    public Field<Long> field2() {
        return MillionsData.MILLIONS_DATA.STAFF_NO;
    }

    @Override
    public Field<BigDecimal> field3() {
        return MillionsData.MILLIONS_DATA.SALARY;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return MillionsData.MILLIONS_DATA.START_TIME;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return MillionsData.MILLIONS_DATA.END_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getStaffNo();
    }

    @Override
    public BigDecimal component3() {
        return getSalary();
    }

    @Override
    public LocalDateTime component4() {
        return getStartTime();
    }

    @Override
    public LocalDateTime component5() {
        return getEndTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getStaffNo();
    }

    @Override
    public BigDecimal value3() {
        return getSalary();
    }

    @Override
    public LocalDateTime value4() {
        return getStartTime();
    }

    @Override
    public LocalDateTime value5() {
        return getEndTime();
    }

    @Override
    public MillionsDataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MillionsDataRecord value2(Long value) {
        setStaffNo(value);
        return this;
    }

    @Override
    public MillionsDataRecord value3(BigDecimal value) {
        setSalary(value);
        return this;
    }

    @Override
    public MillionsDataRecord value4(LocalDateTime value) {
        setStartTime(value);
        return this;
    }

    @Override
    public MillionsDataRecord value5(LocalDateTime value) {
        setEndTime(value);
        return this;
    }

    @Override
    public MillionsDataRecord values(Integer value1, Long value2, BigDecimal value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MillionsDataRecord
     */
    public MillionsDataRecord() {
        super(MillionsData.MILLIONS_DATA);
    }

    /**
     * Create a detached, initialised MillionsDataRecord
     */
    public MillionsDataRecord(Integer id, Long staffNo, BigDecimal salary, LocalDateTime startTime, LocalDateTime endTime) {
        super(MillionsData.MILLIONS_DATA);

        set(0, id);
        set(1, staffNo);
        set(2, salary);
        set(3, startTime);
        set(4, endTime);
    }
}
