/*
 * This file is generated by jOOQ.
 */
package com.pluto.millionsExport.jooqData.tables.records;


import com.pluto.millionsExport.jooqData.tables.TrackingRecord;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 埋点记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TrackingRecordRecord extends UpdatableRecordImpl<TrackingRecordRecord> implements Record13<String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Integer, Byte> {

    private static final long serialVersionUID = 490690541;

    /**
     * Setter for <code>learn.tracking_record.id</code>. 标识
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>learn.tracking_record.id</code>. 标识
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>learn.tracking_record.tracking_id</code>. 唯一编码
     */
    public void setTrackingId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>learn.tracking_record.tracking_id</code>. 唯一编码
     */
    public String getTrackingId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>learn.tracking_record.user_id</code>. 用户id
     */
    public void setUserId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>learn.tracking_record.user_id</code>. 用户id
     */
    public String getUserId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>learn.tracking_record.open_id</code>. 用户微信公众号的openid
     */
    public void setOpenId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>learn.tracking_record.open_id</code>. 用户微信公众号的openid
     */
    public String getOpenId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>learn.tracking_record.patient_id</code>. 患者id
     */
    public void setPatientId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>learn.tracking_record.patient_id</code>. 患者id
     */
    public String getPatientId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>learn.tracking_record.physician_id</code>. 医生id
     */
    public void setPhysicianId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>learn.tracking_record.physician_id</code>. 医生id
     */
    public String getPhysicianId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>learn.tracking_record.event_type</code>. 事件类型
     */
    public void setEventType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>learn.tracking_record.event_type</code>. 事件类型
     */
    public String getEventType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>learn.tracking_record.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>learn.tracking_record.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>learn.tracking_record.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>learn.tracking_record.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>learn.tracking_record.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>learn.tracking_record.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>learn.tracking_record.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>learn.tracking_record.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>learn.tracking_record.revision</code>. 乐观锁
     */
    public void setRevision(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>learn.tracking_record.revision</code>. 乐观锁
     */
    public Integer getRevision() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>learn.tracking_record.deleted</code>. 删除标记
     */
    public void setDeleted(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>learn.tracking_record.deleted</code>. 删除标记
     */
    public Byte getDeleted() {
        return (Byte) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Integer, Byte> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<String, String, String, String, String, String, String, String, LocalDateTime, String, LocalDateTime, Integer, Byte> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return TrackingRecord.TRACKING_RECORD.ID;
    }

    @Override
    public Field<String> field2() {
        return TrackingRecord.TRACKING_RECORD.TRACKING_ID;
    }

    @Override
    public Field<String> field3() {
        return TrackingRecord.TRACKING_RECORD.USER_ID;
    }

    @Override
    public Field<String> field4() {
        return TrackingRecord.TRACKING_RECORD.OPEN_ID;
    }

    @Override
    public Field<String> field5() {
        return TrackingRecord.TRACKING_RECORD.PATIENT_ID;
    }

    @Override
    public Field<String> field6() {
        return TrackingRecord.TRACKING_RECORD.PHYSICIAN_ID;
    }

    @Override
    public Field<String> field7() {
        return TrackingRecord.TRACKING_RECORD.EVENT_TYPE;
    }

    @Override
    public Field<String> field8() {
        return TrackingRecord.TRACKING_RECORD.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return TrackingRecord.TRACKING_RECORD.CREATE_TIME;
    }

    @Override
    public Field<String> field10() {
        return TrackingRecord.TRACKING_RECORD.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return TrackingRecord.TRACKING_RECORD.UPDATE_TIME;
    }

    @Override
    public Field<Integer> field12() {
        return TrackingRecord.TRACKING_RECORD.REVISION;
    }

    @Override
    public Field<Byte> field13() {
        return TrackingRecord.TRACKING_RECORD.DELETED;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTrackingId();
    }

    @Override
    public String component3() {
        return getUserId();
    }

    @Override
    public String component4() {
        return getOpenId();
    }

    @Override
    public String component5() {
        return getPatientId();
    }

    @Override
    public String component6() {
        return getPhysicianId();
    }

    @Override
    public String component7() {
        return getEventType();
    }

    @Override
    public String component8() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component9() {
        return getCreateTime();
    }

    @Override
    public String component10() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component11() {
        return getUpdateTime();
    }

    @Override
    public Integer component12() {
        return getRevision();
    }

    @Override
    public Byte component13() {
        return getDeleted();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTrackingId();
    }

    @Override
    public String value3() {
        return getUserId();
    }

    @Override
    public String value4() {
        return getOpenId();
    }

    @Override
    public String value5() {
        return getPatientId();
    }

    @Override
    public String value6() {
        return getPhysicianId();
    }

    @Override
    public String value7() {
        return getEventType();
    }

    @Override
    public String value8() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value9() {
        return getCreateTime();
    }

    @Override
    public String value10() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value11() {
        return getUpdateTime();
    }

    @Override
    public Integer value12() {
        return getRevision();
    }

    @Override
    public Byte value13() {
        return getDeleted();
    }

    @Override
    public TrackingRecordRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value2(String value) {
        setTrackingId(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value3(String value) {
        setUserId(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value4(String value) {
        setOpenId(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value5(String value) {
        setPatientId(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value6(String value) {
        setPhysicianId(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value7(String value) {
        setEventType(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value8(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value9(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value10(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value11(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value12(Integer value) {
        setRevision(value);
        return this;
    }

    @Override
    public TrackingRecordRecord value13(Byte value) {
        setDeleted(value);
        return this;
    }

    @Override
    public TrackingRecordRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, LocalDateTime value9, String value10, LocalDateTime value11, Integer value12, Byte value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TrackingRecordRecord
     */
    public TrackingRecordRecord() {
        super(TrackingRecord.TRACKING_RECORD);
    }

    /**
     * Create a detached, initialised TrackingRecordRecord
     */
    public TrackingRecordRecord(String id, String trackingId, String userId, String openId, String patientId, String physicianId, String eventType, String createBy, LocalDateTime createTime, String updateBy, LocalDateTime updateTime, Integer revision, Byte deleted) {
        super(TrackingRecord.TRACKING_RECORD);

        set(0, id);
        set(1, trackingId);
        set(2, userId);
        set(3, openId);
        set(4, patientId);
        set(5, physicianId);
        set(6, eventType);
        set(7, createBy);
        set(8, createTime);
        set(9, updateBy);
        set(10, updateTime);
        set(11, revision);
        set(12, deleted);
    }
}
